"""
Configuration package for IoT Financial Data Analytics.

Provides centralized access to all settings and constants organized by domain.

Usage:
    import config
    # Access any setting via config.SETTING_NAME
"""

# Import all assets configuration
from .assets import (
    ASSETS,
    FILE_NAMES,
)

# Import all data configuration
from .data import (
    DATA_BASE_PATH,
    GRANULARITY_PATHS,
    GRANULARITY_DISPLAY,
    COLUMNS,
)

# Import all anomaly detection configuration
from .anomaly import (
    ZSCORE_WARNING_THRESHOLD,
    ZSCORE_ANOMALY_THRESHOLD,
    PERCENTILE_LOW,
    PERCENTILE_HIGH,
    PCT_CHANGE_THRESHOLD_DAILY,
    PCT_CHANGE_THRESHOLD_MINUTE,
    WINDOW_SIZE_MINUTE,
    WINDOW_SIZE_DAILY,
    WINDOW_SIZE_MIN,
    WINDOW_SIZE_MAX,
    CORRELATION_WINDOW,
    CORRELATION_STRONG_POSITIVE,
    CORRELATION_STRONG_NEGATIVE,
    SYSTEMIC_EVENT_THRESHOLD,
    SIM_SPEED_MIN,
    SIM_SPEED_MAX,
    SIM_SPEED_DEFAULT,
    MAX_ANOMALIES_IN_CONTEXT,
    MAX_REALTIME_ANOMALIES_DISPLAY,
    MAX_SYSTEMIC_EVENTS_DISPLAY,
)

# Import all pattern recognition configuration
from .patterns import (
    DOJI_BODY_RATIO,
    HAMMER_SHADOW_RATIO,
    PEAK_DISTANCE,
    PEAK_PROMINENCE_PCT,
    SMOOTHING_WINDOW,
    DOJI_BODY_RATIO_DEFAULT,
    HAMMER_BODY_RATIO_DEFAULT,
    HAMMER_SHADOW_RATIO_DEFAULT,
    CHART_PATTERN_LOOKBACK_DEFAULT,
    CHART_PATTERN_LOOKBACK_MIN,
    CHART_PATTERN_LOOKBACK_MAX,
    PRICE_TOLERANCE_MIN,
    PRICE_TOLERANCE_MAX,
    PRICE_TOLERANCE_DEFAULT,
    PRICE_TOLERANCE_STEP,
    PROMINENCE_MIN,
    PROMINENCE_MAX,
    PROMINENCE_DEFAULT,
    PROMINENCE_STEP,
    MAX_PATTERNS_IN_CONTEXT,
)

# Import all UI configuration
from .ui import (
    PAGE_TYPE_SINGLE_ASSET,
    PAGE_TYPE_REALTIME,
    PAGE_TYPE_CROSS_ASSET,
    PAGE_TYPE_PATTERNS,
    PAGE_TYPES,
    PAGE_TITLE,
    PAGE_ICON,
    LAYOUT,
    COLOR_NORMAL,
    COLOR_WARNING,
    COLOR_ANOMALY,
    COLOR_BULLISH,
    COLOR_BEARISH,
    MARKER_SIZE_NORMAL,
    MARKER_SIZE_ANOMALY,
    CHAT_MESSAGES_HEIGHT,
    MAX_CHARTS_IN_CONTEXT,
    INITIAL_MESSAGE_DISPLAY_COUNT,
    CHART_EXPORT_WIDTH,
    CHART_EXPORT_HEIGHT,
    CHART_EXPORT_SCALE,
    SCROLL_DEBOUNCE_MS,
    SCROLL_INITIAL_WAIT_MS,
    DEFAULT_CHART_CONFIG,
    CHART_CONFIG_WITH_MODEBAR,
)

# Import all AI configuration
from .ai import (
    GEMINI_MODEL,
    GEMINI_MAX_TOKENS,
    GEMINI_TEMPERATURE,
    GEMINI_HISTORY_LENGTH,
    GEMINI_API_KEY_ENV,
    GEMINI_CHAT_TITLE,
    GEMINI_CHAT_PLACEHOLDER,
    GEMINI_CHAT_WIDTH,
    GEMINI_SYSTEM_PROMPT,
    GEMINI_MOCK_RESPONSE,
)

# Import all logging configuration
from .logging import (
    LOG_LEVEL,
    ENABLE_FILE_LOGGING,
    LOG_FILE_PATH,
    LOG_FILE_ROTATION,
    LOG_FILE_RETENTION,
    LOG_FILE_COMPRESSION,
    LOG_FORMAT,
    LOG_FORMAT_PRODUCTION,
)

# Import all data attachment configuration
from .attachment import (
    DATA_OPTIONS,
    PAGE_SUGGESTIONS
)

# Export all for 'from config import *' (though not recommended)
__all__ = [
    # Assets
    'ASSETS', 'FILE_NAMES',
    
    # Data
    'DATA_BASE_PATH', 'GRANULARITY_PATHS', 'GRANULARITY_DISPLAY', 'COLUMNS',
    
    # Anomaly detection
    'ZSCORE_WARNING_THRESHOLD', 'ZSCORE_ANOMALY_THRESHOLD',
    'PERCENTILE_LOW', 'PERCENTILE_HIGH',
    'PCT_CHANGE_THRESHOLD_DAILY', 'PCT_CHANGE_THRESHOLD_MINUTE',
    'WINDOW_SIZE_MINUTE', 'WINDOW_SIZE_DAILY', 'WINDOW_SIZE_MIN', 'WINDOW_SIZE_MAX',
    'CORRELATION_WINDOW', 'CORRELATION_STRONG_POSITIVE', 'CORRELATION_STRONG_NEGATIVE',
    'SYSTEMIC_EVENT_THRESHOLD',
    'SIM_SPEED_MIN', 'SIM_SPEED_MAX', 'SIM_SPEED_DEFAULT',
    'MAX_ANOMALIES_IN_CONTEXT', 'MAX_REALTIME_ANOMALIES_DISPLAY',
    'MAX_SYSTEMIC_EVENTS_DISPLAY',
    
    # Pattern recognition
    'DOJI_BODY_RATIO', 'HAMMER_SHADOW_RATIO',
    'PEAK_DISTANCE', 'PEAK_PROMINENCE_PCT', 'SMOOTHING_WINDOW',
    'DOJI_BODY_RATIO_DEFAULT', 'HAMMER_BODY_RATIO_DEFAULT', 'HAMMER_SHADOW_RATIO_DEFAULT',
    'CHART_PATTERN_LOOKBACK_DEFAULT', 'CHART_PATTERN_LOOKBACK_MIN',
    'CHART_PATTERN_LOOKBACK_MAX',
    'PRICE_TOLERANCE_MIN', 'PRICE_TOLERANCE_MAX', 'PRICE_TOLERANCE_DEFAULT',
    'PRICE_TOLERANCE_STEP',
    'PROMINENCE_MIN', 'PROMINENCE_MAX', 'PROMINENCE_DEFAULT', 'PROMINENCE_STEP',
    'MAX_PATTERNS_IN_CONTEXT',
    
    # UI
    'PAGE_TYPE_SINGLE_ASSET', 'PAGE_TYPE_REALTIME', 'PAGE_TYPE_CROSS_ASSET',
    'PAGE_TYPE_PATTERNS', 'PAGE_TYPES',
    'PAGE_TITLE', 'PAGE_ICON', 'LAYOUT',
    'COLOR_NORMAL', 'COLOR_WARNING', 'COLOR_ANOMALY', 'COLOR_BULLISH', 'COLOR_BEARISH',
    'MARKER_SIZE_NORMAL', 'MARKER_SIZE_ANOMALY',
    'CHAT_MESSAGES_HEIGHT', 'MAX_CHARTS_IN_CONTEXT', 'INITIAL_MESSAGE_DISPLAY_COUNT',
    'CHART_EXPORT_WIDTH', 'CHART_EXPORT_HEIGHT', 'CHART_EXPORT_SCALE',
    'SCROLL_DEBOUNCE_MS', 'SCROLL_INITIAL_WAIT_MS',
    'DEFAULT_CHART_CONFIG', 'CHART_CONFIG_WITH_MODEBAR',
    
    # AI
    'GEMINI_MODEL', 'GEMINI_MAX_TOKENS', 'GEMINI_TEMPERATURE',
    'GEMINI_HISTORY_LENGTH', 'GEMINI_API_KEY_ENV',
    'GEMINI_CHAT_TITLE', 'GEMINI_CHAT_PLACEHOLDER', 'GEMINI_CHAT_WIDTH',
    'GEMINI_SYSTEM_PROMPT', 'GEMINI_MOCK_RESPONSE',
    
    # Logging
    'LOG_LEVEL', 'ENABLE_FILE_LOGGING', 'LOG_FILE_PATH',
    'LOG_FILE_ROTATION', 'LOG_FILE_RETENTION', 'LOG_FILE_COMPRESSION',
    'LOG_FORMAT', 'LOG_FORMAT_PRODUCTION',

    # Attachment
    'DATA_OPTIONS', 'PAGE_SUGGESTIONS'
]
